### ISSUE TITLE
Product Backlog

### ISSUE THREAD

**Issue by iotos** [nutriotos/nutriotos#6]
Seguem aqui as tarefas a serem feitas nesse projeto e a cada tarefa que necessita ser criada, comente nessa issue.
Se tiver layout ou wireframe da tela a ser desenvolvida, colocar o link para o acesso.
Se for uma funcionalidade, colocar descrição bem detalhada e, se tiver, link para o acesso com detalhes.

**Comment by iotos** [comment]
- [ ] Página de login do sistema - [link](https://drive.google.com/open?id=0B_7Gq34cVpEvVFpIS1VyUWlxeFE) - #7 
- [ ] Página inicial do sistema - [link](https://drive.google.com/open?id=0B_7Gq34cVpEvb3RyVlZtdEVfNlk)

Os links são de imagens jpg e é só uma referência para telas. Maiores detalhes nas issues de cada tarefa.

**Comment by iotos** [comment]
- [ ] Página de cadastro do Nutricionista - #8

**Comment by iotos** [comment]
- [ ] Página de cadastro do paciente - #9

**Comment by iotos** [comment]
- [ ] Agenda do sistema - #10
